apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - ingress.yaml
  - watcher-nodes.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: homelab
    includeSelectors: false
# Note: Longhorn installed via Helm
# helm install longhorn longhorn/longhorn -n longhorn-system
