apiVersion: v1
kind: Service
metadata:
  name: outline
  namespace: outline
  labels:
    app.kubernetes.io/name: outline
    app.kubernetes.io/component: wiki
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: outline
  ports:
  - port: 3000
    targetPort: http
    name: http
