apiVersion: v1
kind: Service
metadata:
  name: nfs-proxy
  namespace: nfs-proxy
  labels:
    app.kubernetes.io/name: nfs-proxy
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nfs-proxy
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP
    - name: nfs-udp
      port: 2049
      targetPort: 2049
      protocol: UDP
    - name: mountd
      port: 20048
      targetPort: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      targetPort: 111
      protocol: TCP
    - name: statd
      port: 32765
      targetPort: 32765
      protocol: TCP
    - name: statd-udp
      port: 32765
      targetPort: 32765
      protocol: UDP
    - name: lockd
      port: 32767
      targetPort: 32767
      protocol: TCP
    - name: lockd-udp
      port: 32767
      targetPort: 32767
      protocol: UDP
